[package]
name = "geoserde"
version = "0.5.3-beta.1"
edition = "2024"
description = "Adapter between Rust data structures and geospatial file formats"
repository = "https://github.com/p4ken/geoserde"
license = "MIT"
exclude = [".*"]

[package.metadata.docs.rs]
all-features = true

[features]
default = ["geo"]
geo = ["dep:geo-types"]
fgb = ["dep:flatgeobuf"]

[dependencies]
serde = { version = "1.0.214", features = ["derive"] }
geo-types = { version = "0.7.11", optional = true }
geo-traits = { version = "0.3.0" }
flatgeobuf = { version = "6.0.1", default-features = false, optional = true }
# NOTE: Should be re-exported by flatgeobuf
flatbuffers = { version = "24", default-features = false }

[dev-dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
flatgeobuf = { version = "6.0.1", default-features = false }
geo-types = { version = "0.7.11", features = ["serde"] }
geozero = { version = "0.15.0" }
