[workspace]

[workspace.package]
edition = "2024"
description = "Adapter between Rust data structures and geospatial file formats"
repository = "https://github.com/p4ken/geoserde"
license = "MIT"
exclude = [".*"]

[package]
name = "geoserde"
version = "0.5.2"
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
exclude.workspace = true

[features]
default = [
    "fgb",
    "geo",
]
shapefile = ["dep:shapefile", "dbase"]
geo = ["dep:geo-types"]
fgb = ["dep:flatgeobuf"]

[dependencies]
serde = { version = "1.0.214", features = ["derive"] }
geo-types = { version = "0.7.11", optional = true }
geo-traits = { version = "0.3.0" }
# Only the way to enable serde for shapefile
dbase = { version = "0.5.0", features = ["serde"], optional = true }
shapefile = { version = "0.6.0", features = ["geo-types"], optional = true }
geojson = { version = "0.24.2", optional = true }
flatgeobuf = { version = "6.0.1", default-features = false, optional = true }
# Should be re-exported by flatgeobuf
flatbuffers = { version = "24", default-features = false }

[dev-dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
flatgeobuf = { version = "6.0.1", default-features = false }
geo-types = { version = "0.7.11", features = ["serde"] }
geojson = { version = "0.24.2" }
geozero = { version = "0.15.0", features = ["with-geo"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = { version = "1.0.149", features = ["preserve_order"] }
shapefile = { version = "0.6.0", features = ["geo-types"] }
