[workspace]
members = ["fgb"]
default-members = [".", "fgb"]

[workspace.package]
edition = "2024"
repository = "https://github.com/p4ken/geoserde"
license = "MIT"

[package]
name = "geoserde"
version = "0.5.3-beta.1"
edition.workspace = true
description = "Adapter between Rust data structures and geospatial file formats"
repository.workspace = true
license.workspace = true
exclude = [".*"]
# TODO: keywords = ["gis", "geospatial", "serde", "geo"] (最大5個)
# TODO: categories = ["science::geo", "encoding"] (https://crates.io/category_slugs から選ぶ)

[package.metadata.docs.rs]
all-features = true

[features]
default = ["geo"]
geo = ["dep:geo-types", "geo-traits/geo-types"]

[dependencies]
serde = { version = "1.0.214", features = ["derive"] }
geo-types = { version = "0.7.11", optional = true }
geo-traits = { version = "0.3.0", default-features = false }
