[package]
name = "geoserde-fgb"
version = "0.1.0-beta.0"
edition.workspace = true
description = "Read and write FlatGeobuf features as your own Rust data structures"
repository.workspace = true
license.workspace = true
# TODO: keywords = ["gis", "geospatial", "serde", "flatgeobuf", "fgb"] (最大5個)
# TODO: categories = ["science::geo", "encoding", "parser-implementations"]

[package.metadata.docs.rs]
all-features = true

[features]
default = ["geo-types"]
geo-types = ["geoserde/geo-types"]

[dependencies]
geoserde = { version = "0.5.3-beta.1", path = "..", default-features = false }
serde = { version = "1.0.214" }
geo-traits = { version = "0.3.0", default-features = false }
flatgeobuf = { version = "6.0.1", default-features = false }

[dev-dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
geo-types = { version = "0.7.11", features = ["serde"] }
geozero = { version = "0.15.0" }
