name: Release
on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        options:
          - patch
          - minor
      dry_run:
        type: boolean
permissions:
  contents: write
env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
jobs:
  Publish:
    runs-on: ubuntu-latest
    environment:
      name: crates.io
    steps:
    - uses: actions/checkout@v4
    - run: cargo install cargo-edit
    # - run: cargo bump --package jgd ${{ inputs.bump }}
    # - uses: fregante/setup-git-user@v2
    # - run: git commit --all --message "v$(make version)"
    # - run: git tag "v$(make version)" --message ""
    # - run: git push --follow-tags
    # - run: cargo publish
