name: Release
on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        options:
          - patch
          - minor
      package:
        type: choice
        options:
          - --package geoserde
          - --workspace
      dry-run:
        type: boolean
        default: true
permissions:
  contents: write
env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: cargo install cargo-edit
    - run: cargo set-version --bump ${{ inputs.bump }} ${{ inputs.package }}
    - run: git commit --all --message "v$(make version)"
    - run: git tag "v$(make version)"
    - run: git push --tags origin HEAD ${{ inputs.dry-run && '--dry-run' || '' }}
    - run: cargo publish ${{ inputs.package }} ${{ inputs.dry-run && '--dry-run' || '' }}
